name: Create Conda Environments in Docker

on:
  workflow_dispatch:
    inputs:
      subset:
        description: 'Comma-separated list of environments to skip. Leave blank to build all.'
        required: false

env:
  METPLUS_ENV_VERSION: v6.0-test
  DOCKERFILE: Dockerfile
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  conda:
    name: "Create conda env"
    runs-on: ubuntu-latest
    env:
      ENV_NAME: conda
      DOCKERFILE: Dockerfile.conda
    steps:
      - uses: actions/checkout@v4
        with:
          path: ghatest
      - uses: actions/checkout@v4
        with:
          repository: 'dtcenter/METplus'
          sparse-checkout: internal
          path: METplus
      - name: Build
        run: ghatest/.github/jobs/build_conda_image.sh
      - name: Push
        run: ghatest/.github/jobs/push_conda_image.sh

  metplus_base:
    name: "Create metplus_base env"
    runs-on: ubuntu-latest
    needs: [conda]
    env:
      ENV_NAME: metplus_base
      DOCKERFILE: Dockerfile.metplus_base
    steps:
      - uses: actions/checkout@v4
        with:
          path: ghatest
      - uses: actions/checkout@v4
        with:
          repository: 'dtcenter/METplus'
          sparse-checkout: internal
          path: METplus
      - name: Build
        run: ghatest/.github/jobs/build_conda_image.sh
      - name: Push
        run: ghatest/.github/jobs/push_conda_image.sh

  py_embed_base:
    name: "Create py_embed_base env"
    runs-on: ubuntu-latest
    needs: [metplus_base]
    env:
      ENV_NAME: py_embed_base
      DOCKERFILE: Dockerfile.py_embed_base
    steps:
      - uses: actions/checkout@v4
        with:
          path: ghatest
      - uses: actions/checkout@v4
        with:
          repository: 'dtcenter/METplus'
          sparse-checkout: internal
          path: METplus
      - name: Build
        run: ghatest/.github/jobs/build_conda_image.sh
      - name: Push
        run: ghatest/.github/jobs/push_conda_image.sh

  h5py:
    runs-on: ubuntu-latest
    needs: [py_embed_base]
    env:
      ENV_NAME: h5py
      BASE_ENV: py_embed_base
    steps:
      - uses: actions/checkout@v4
        with:
          path: ghatest
      - uses: actions/checkout@v4
        with:
          repository: 'dtcenter/METplus'
          sparse-checkout: internal
          path: METplus
      - name: Build
        run: ghatest/.github/jobs/build_conda_image.sh
      - name: Push
        run: ghatest/.github/jobs/push_conda_image.sh
