name: Create Conda Environments in Docker

on:
  workflow_dispatch:
    inputs:
      subset:
        description: 'Comma-separated list of environments to skip. Leave blank to build all.'
        required: false

env:
  METPLUS_ENV_VERSION: v6.0-test
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  conda:
    name: "Create conda env"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ghatest
      - uses: actions/checkout@v4
        with:
          repository: 'dtcenter/METplus'
          sparse-checkout: internal
          path: METplus
      - name: Build
        run: ghatest/.github/jobs/build_conda_image.sh
        env:
          IMG_NAME: conda
          DOCKERFILE: Dockerfile.conda

      - name: Push
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          echo docker push dtcenter/metplus-envs:conda.${METPLUS_ENV_VERSION}
          docker push dtcenter/metplus-envs:conda.${METPLUS_ENV_VERSION}

  metplus_base:
    name: "Create metplus_base env"
    runs-on: ubuntu-latest
    needs: [conda]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'dtcenter/METplus'
      - name: Build
        run: |
          cd internal/scripts/docker_env
          echo docker build -t dtcenter/metplus-envs:metplus_base.${METPLUS_ENV_VERSION} \
            --build-arg METPLUS_ENV_VERSION \
            -f Dockerfile.metplus_base .
          docker build -t dtcenter/metplus-envs:metplus_base.${METPLUS_ENV_VERSION} \
            --build-arg METPLUS_ENV_VERSION \
            -f Dockerfile.metplus_base .
      - name: Push
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          echo docker push dtcenter/metplus-envs:metplus_base.${METPLUS_ENV_VERSION}
          docker push dtcenter/metplus-envs:metplus_base.${METPLUS_ENV_VERSION}
