on:
  push:
    branches:
      - test_external_trigger
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository that triggered workflow'
        required: true
      docker_tag:
        description: 'DockerHub tag to use'
      actor:
        description: 'User that triggered the event'
        required: true

jobs:
  get_trigger_info:
    name: Get information about what triggered this workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub values for reference
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
