on:
  push:
    branches:
      - test_external_trigger
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository that triggered workflow'
        required: true
      docker_tag:
        description: 'DockerHub tag to use'
      actor:
        description: 'User that triggered the event'
        required: true
      pusher_email:
        description: 'Email address of user who triggered push event'

jobs:
  trigger_info:
    name: "Trigger: ${{ github.event_name != 'workflow_dispatch' && 'github.event_name github.job' || 'github.event.inputs.repository github.event.inputs.pusher_email github.event.inputs.sha' }}"
    #name: "Trigger: ${{ github.event_name != 'workflow_dispatch' && github.event_name || github.event.inputs.repo_name }}"
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs from Event
        run: |
          echo "repo_name: ${{ github.event.inputs.repo_name }}"
          echo "docker_tag: ${{ github.event.inputs.docker_tag }}"
          echo "actor: ${{ github.event.inputs.actor }}"
  get_trigger_info:
    name: Get information about what triggered this workflow
    runs-on: ubuntu-latest
    outputs:
      trigger_text: ${{ steps.get_trigger_info.outputs.trigger_text }}
    steps:
      - name: Read event info
        run: |
          if [ ${{ github.event_name == 'workflow_dispatch' }} ]; then
            str="From ${{ github.event.inputs.repo_name }} by ${{ github.event.inputs.actor }}"
          else
            str="${{ github.event_name }} Event"
          fi
          echo ::set-output name=trigger_text::$str
      - name: Print GitHub values for reference
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  print_event:
    needs: get_trigger_info
    name: ${{ needs.get_trigger_info.outputs.trigger_text }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs from Event
        run: |
          echo "repo_name: ${{ github.event.inputs.repo_name }}"
          echo "docker_tag: ${{ github.event.inputs.docker_tag }}"
          echo "actor: ${{ github.event.inputs.actor }}"
          echo "pusher_email: ${{ github.event.inputs.pusher_email }}"
      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "TEST: ${{ github.repository }} Use Case Tests Failed"
          body: "A METplus use case testing workflow failed after it was triggered by changes you p\
ushed in REPO COMMIT_HASH. Changes from your push did not necessarily break the tests. It is possi\
ble that the tests were failing prior to your push. Please investigate the differences that may ha\
ve been caused by your changes. https://github.com/${{github.repository}}/actions/runs/${{github.r\
un_id}}"
          to: "metplus-bot@ucar.edu mccabe@ucar.edu"
          from: George via Automation
