name: Subset List Test

on:
  push:
  workflow_dispatch:
    inputs:
      subset:
        description: 'Comma-separated list of environments to skip. Leave blank to build all.'
        required: false

env:
  SKIP_LIST: 'two   four'

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ env.SKIP_LIST }}
      - id: combine
        run: |
          skip_str=${{ env.SKIP_LIST }}
          arr=()
          for i in $(seq 1 30); do val=$(echo $skip_str | awk -F '{print ${!i}'); echo $val; arr[${#arr[@]}]=$val;done
          #for i in $(seq 0 $((${{ steps.split.outputs.length }}-1))); do name="steps.split.outputs._$i"; echo ${{ $name }}; arr[${#arr[@]}]=$i;done
          echo "skip_list=$arr" >> $GITHUB_OUTPUT
          echo ${arr[@]}
    outputs:
      skip_list: ${{ steps.combine.outputs.skip_list }}
  one:
    runs-on: ubuntu-latest
    needs: [skip]
    steps:
      - name: Run
        run: echo ran this one!
      - run: echo ${{ needs.skip.outputs.skip_list }}

  two:
    runs-on: ubuntu-latest
    needs: [skip,one]
    steps:
      - name: Run
        run: echo ran this one!

  three:
    runs-on: ubuntu-latest
    needs: [skip,one]
    steps:
      - name: Run
        run: echo ran this one!

  four:
    runs-on: ubuntu-latest
    needs: [skip]
    steps:
      - name: Run
        run: echo ran this one!

  five:
    runs-on: ubuntu-latest
    needs: [skip,three]
    steps:
      - name: Run
        run: echo ran this one!
