name: Test Matrix
on:
  push:
    branches:
      - 'test_matrix'

jobs:
  pre1:
    runs-on: ubuntu-latest
    steps:
      - run: echo Running pre job 1
  pre2:
    runs-on: ubuntu-latest
    steps:
      - run: echo Running pre job 2

  ${{ matrix.tests }}:
    name: Run MET Unit Tests
    runs-on: ubuntu-latest
    #needs: [pre1, ${{ matrix.needed }}]
    needs: [pre1]
    id: ${{ matrix.tests }}
    strategy:
      matrix:
        needed: pre2
        tests:
          - 'gaussian'
          - 'airnow'
        include:
          - tests: 'ioda2nc'
            needed: 'pre2, airnow'
      fail-fast: false
    steps:
      - run: echo ${{ matrix.tests }}
