name: Test Action
on:
  push:
    branches:
      - 'test_action'

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - uses: dtcenter/metplus-data-update@5b58f1b843dfe29222c15fcf902b1a27ac9ae272
        with:
          docker_name: ${{ secrets.DOCKER_USERNAME }}
          docker_pass: ${{ secrets.DOCKER_PASSWORD }}
          repo_name: MET
          data_prefix: unit_test
          branch_name: develop
          data_repo_dev: met-data-dev
          docker_data_dir: /data/input/MET_test_data/unit_test
