name: Test Action
on:
  push:
    branches:
      - 'test_action'

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - uses: dtcenter/metplus-data-update@f5fd24cfbb48ee33e934a3756c8e9832e6c62fbd
        with:
          docker_name: bad_name
          docker_pass: bad_pass
          repo_name: MET
          data_prefix: unit_test
          branch_name: develop
          data_repo_dev: met-data-dev
          docker_data_dir: /data/input/MET_test_data/unit_test
