name: Trigger METplus Workflow

on:
  push:
    branches:
      - develop
      - main_v**
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '**/README.md'
      - '**/LICENSE.md'

jobs:
  trigger_metplus:
    name: Trigger METplus testing workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub values for reference
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'dtcenter/METplus'
          ref: 'develop'
          path: 'METplus'
      - run: ls $GITHUB_WORKSPACE
      - id: get_version
        run: |
          version=$(python3 -c "from component_name import __version__; print(__version__)")
          echo "version=${version}" >> $GITHUB_OUTPUT
      - run: |
          repo=${{ github.repository }}
          repo=${repo#*/}
          echo repo is ${repo}
          version=${{ steps.get_version.outputs.version }}
          cmd="$GITHUB_WORKSPACE/METplus/metplus/component_versions.py -i METplotpy -v ${version} -o METplus -f main_v{X}.{Y}"
          echo $cmd
          $cmd
#      - uses: actions/github-script@v7
#        with:
#          github-token: ${{ secrets.METPLUS_BOT_TOKEN }}
#          script: |
#            await github.rest.actions.createWorkflowDispatch({
#              owner: 'dtcenter',
#              repo: 'METplus',
#              workflow_id: 'testing.yml',
#              ref: 'develop',
#              inputs: {
#                repository: '${{ github.repository }}',
#                ref: '${{ github.ref }}',
#                actor: '${{ github.actor }}',
#                sha: '${{ github.sha }}',
#                pusher_email: '${{ github.event.pusher.email }}'
#              },
#            });
