name: Trigger METplus Workflow

on:
  push:
    branches:
      - develop
      - 'main_v[0-9]+.[0-9]+'
    paths-ignore:
      - 'docs/**'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '**/README.md'
      - '**/LICENSE.md'

jobs:
  trigger_metplus:
    name: Trigger METplus testing workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub values for reference
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: dtcenter/metplus-action-trigger-use-cases@093f16857a42b53798bba63410c8cbfaaf8e3e93
        with:
          token: ${{ secrets.METPLUS_BOT_TOKEN }}
#      - name: Checkout code from this repo
#        uses: actions/checkout@v4
#      - name: Get METplus repo for component version script
#        uses: actions/checkout@v4
#        with:
#          repository: 'dtcenter/METplus'
#          ref: 'develop'
#          path: 'METplus'
#      - name: Get version from ref (branch)
#      - id: get_version
#        run: |
#          version=$(cut -d "/" -f3 <<< "${GITHUB_REF}")
#          echo "version=${version}" >> $GITHUB_OUTPUT
#      - id: get_metplus_branch
#        run: |
#          repo=${{ github.repository }}
#          repo=${repo#*/}
#          version=${{ steps.get_version.outputs.version }}
#          cmd="$GITHUB_WORKSPACE/METplus/metplus/component_versions.py -i ${repo} -v ${version} -o METplus -f main_v{X}.{Y}"
#          echo $cmd
#          metplus_branch=$($cmd)
#          # if no branch can be determined, exit and error
#          if [ -z "${metplus_branch}" ]; then
#            echo "ERROR: Could not get METplus branch"
#            exit 1
#          fi
#          branch_exists=$(git -C $GITHUB_WORKSPACE/METplus ls-remote origin ${metplus_branch})
#          if [ -z "${branch_exists}" ]; then
#            echo "METplus branch ${metplus_branch} does not exist yet"
#            metplus_branch=none
#          fi
#          echo "metplus_branch=${metplus_branch}" >> $GITHUB_OUTPUT
#      - if: ( steps.get_metplus_branch.outputs.metplus_branch  != 'none' )
#        run: |
#          metplus_branch=${{ steps.get_metplus_branch.outputs.metplus_branch }}
#          echo "Triggering workflow dispatch of ${metplus_branch}"
#      - if: ( steps.get_metplus_branch.outputs.metplus_branch  != 'none' )
#        uses: actions/github-script@v7
#        with:
#          github-token: ${{ secrets.METPLUS_BOT_TOKEN }}
#          script: |
#            await github.rest.actions.createWorkflowDispatch({
#              owner: 'dtcenter',
#              repo: 'METplus',
#              workflow_id: 'testing.yml',
#              ref: ${{ steps.get_metplus_branch.outputs.metplus_branch }},
#              inputs: {
#                repository: '${{ github.repository }}',
#                ref: '${{ github.ref }}',
#                actor: '${{ github.actor }}',
#                sha: '${{ github.sha }}',
#                pusher_email: '${{ github.event.pusher.email }}'
#              },
#            });
