name: Update Truth Data

on:
  workflow_dispatch:


jobs:
  update_truth:
    name: "Update or create truth reference branch"
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is valid
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          if [[ $branch_name == "develop" ]]; then exit 0; fi
          if [[ ${branch_name:0:6} =~ ^main_v[0-9]\.[0-9]$ ]]; then exit 0; fi
          echo Branch ($branch_name) must be develop or match main_vX.Y
          exit 1
      - uses: actions/checkout@v3