name: Update Truth Data

on:
  workflow_dispatch:
    inputs:
      pull_requests:
        description: 'Pull request(s) that warranted update, e.g. #123 dtcenter/MET#123'
        required: true
      change_summary:
        description: 'Summary of changes'
        required: true

jobs:
  update_truth:
    name: "Update or create truth reference branch"
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is valid
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          if [[ $branch_name == "develop" ]]; then exit 0; fi
          if [[ $branch_name =~ ^main_v[0-9]+\.[0-9]+$ ]]; then exit 0; fi
          echo Branch is $branch_name - must be develop or match main_vX.Y
          exit 1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if ref branch exists
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          cd ${GITHUB_WORKSPACE}
          if [[ -z "$(git ls-remote --heads origin ${branch_name}-ref)" ]]; then
            echo ${branch_name}-ref does not exist -- create it from $branch_name
            echo git checkout -b ${branch_name}-ref
            git checkout -b ${branch_name}-ref
            echo git push origin ${branch_name}-ref
            git push origin ${branch_name}-ref
          else
            echo ${branch_name}-ref does exist -- update it
            echo git merge -s ours ${branch_name}-ref
            git merge -s ours ${branch_name}-ref
            echo git push origin ${branch_name}
            git push origin ${branch_name}
          fi
          echo Title: Update ${branch_name}-ref after ${{ github.event.inputs.pull_requests }}
          echo Body: Change summary: ${{ github.event.inputs.change_summary }}
